# Form implementation generated from reading ui file 'appdesign.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from datetime import datetime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 410)
        font_italic = QtGui.QFont()
        font_italic.setFamily("MS Serif")
        font_italic.setItalic(True)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit_what_happened = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit_what_happened.setGeometry(QtCore.QRect(40, 220, 241, 87))
        self.plainTextEdit_what_happened.setObjectName("plainTextEdit_what_happened")
        self.label_quote = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_quote.setGeometry(QtCore.QRect(50, 70, 221, 81))
        self.label_quote.setFont(font_italic)
        self.label_quote.setScaledContents(False)
        self.label_quote.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_quote.setWordWrap(True)
        self.label_quote.setObjectName("label_quote")
        self.label_streak = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_streak.setGeometry(QtCore.QRect(110, 10, 131, 51))
        self.label_streak.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_streak.setObjectName("label_streak")
        self.label_streak_days = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_streak_days.setGeometry(QtCore.QRect(54, -40, 61, 153))
        self.label_streak_days.setFont(font)
        self.label_streak_days.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_streak_days.setObjectName("label_streak_days")
        self.label_Rateurday = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Rateurday.setGeometry(QtCore.QRect(50, 180, 88, 15))
        self.label_Rateurday.setObjectName("label_Rateurday")
        self.label_keepitgoing_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_keepitgoing_2.setGeometry(QtCore.QRect(-50, 40, 221, 51))
        self.label_keepitgoing_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_keepitgoing_2.setObjectName("label_keepitgoing_2")
        self.label_quote_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_quote_name.setGeometry(QtCore.QRect(150, 130, 221, 51))
        self.label_quote_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_quote_name.setObjectName("label_quote_name")
        self.label_haveagreatnight = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_haveagreatnight.setGeometry(QtCore.QRect(60, 350, 221, 51))
        self.label_haveagreatnight.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_haveagreatnight.setObjectName("label_haveagreatnight")
        self.comboBox_grade = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_grade.setGeometry(QtCore.QRect(200, 180, 80, 22))
        self.comboBox_grade.setMaxVisibleItems(4)
        self.comboBox_grade.setObjectName("comboBox_grade")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.comboBox_grade.addItem("")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 320, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_grade.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"{datetime.now().date()}"))
        self.plainTextEdit_what_happened.setPlainText(_translate("MainWindow", "What happend?"))
        self.label_quote.setText(_translate("MainWindow", "quote"))
        self.label_streak.setText(_translate("MainWindow", "days streak !!"))
        self.label_streak_days.setText(_translate("MainWindow", "1"))
        self.label_Rateurday.setText(_translate("MainWindow", "Rate your day"))
        self.label_keepitgoing_2.setText(_translate("MainWindow", "Today\'s quote"))
        self.label_quote_name.setText(_translate("MainWindow", "name"))
        self.label_haveagreatnight.setText(_translate("MainWindow", "If done, click the button."))
        self.comboBox_grade.setCurrentText(_translate("MainWindow", "bad"))
        self.comboBox_grade.setItemText(0, _translate("MainWindow", "bad"))
        self.comboBox_grade.setItemText(1, _translate("MainWindow", "not bad"))
        self.comboBox_grade.setItemText(2, _translate("MainWindow", "good"))
        self.comboBox_grade.setItemText(3, _translate("MainWindow", "great"))
        self.pushButton.setText(_translate("MainWindow", "call it a day!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
